// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo9C1twKKU8ZCgm2THlMcur7CoI24Z_U0',
    appId: '1:424040780172:web:33dfb9cdbd46c150bfc6a9',
    messagingSenderId: '424040780172',
    projectId: 'new-one-99bf7',
    authDomain: 'new-one-99bf7.firebaseapp.com',
    storageBucket: 'new-one-99bf7.appspot.com',
    measurementId: 'G-HYVC66V4WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbPj_jNF8AStspSnHT6SqL81MnYCSeTk',
    appId: '1:424040780172:android:2b15f7d0899777f2bfc6a9',
    messagingSenderId: '424040780172',
    projectId: 'new-one-99bf7',
    storageBucket: 'new-one-99bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXh7mGMe166CfGxMDOip8nHPE4AWtI4mU',
    appId: '1:424040780172:ios:33c97225b7c152bcbfc6a9',
    messagingSenderId: '424040780172',
    projectId: 'new-one-99bf7',
    storageBucket: 'new-one-99bf7.appspot.com',
    androidClientId: '424040780172-lo5fmk8rrrl847fj5p170abv2tu7dddh.apps.googleusercontent.com',
    iosClientId: '424040780172-q3jm9kk7ba3v48n3cn4qgvgvmcdi0bda.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashtion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXh7mGMe166CfGxMDOip8nHPE4AWtI4mU',
    appId: '1:424040780172:ios:7320757d4601fce3bfc6a9',
    messagingSenderId: '424040780172',
    projectId: 'new-one-99bf7',
    storageBucket: 'new-one-99bf7.appspot.com',
    androidClientId: '424040780172-lo5fmk8rrrl847fj5p170abv2tu7dddh.apps.googleusercontent.com',
    iosClientId: '424040780172-9as4u0t4ien0qid7uphuhrq2udhvgsmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashtion.RunnerTests',
  );
}
