// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJawLSShh54cMU6C2jgPJatTF0WVem1NU',
    appId: '1:1026076349855:web:b81c8d58d265c53e9fd9aa',
    messagingSenderId: '1026076349855',
    projectId: 'portfolio-70b10',
    authDomain: 'portfolio-70b10.firebaseapp.com',
    storageBucket: 'portfolio-70b10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVsEGKduIOlYP1E8YMEMZLcGnnpdH0b1U',
    appId: '1:1026076349855:android:3ace21b309b7578c9fd9aa',
    messagingSenderId: '1026076349855',
    projectId: 'portfolio-70b10',
    storageBucket: 'portfolio-70b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5PV6FzKYQn5OGMXOhdJtl4RxSe7Xb7bU',
    appId: '1:1026076349855:ios:9462a7efa716d2e19fd9aa',
    messagingSenderId: '1026076349855',
    projectId: 'portfolio-70b10',
    storageBucket: 'portfolio-70b10.appspot.com',
    iosBundleId: 'com.example.fashtion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5PV6FzKYQn5OGMXOhdJtl4RxSe7Xb7bU',
    appId: '1:1026076349855:ios:4f7fa5c4b3d45a649fd9aa',
    messagingSenderId: '1026076349855',
    projectId: 'portfolio-70b10',
    storageBucket: 'portfolio-70b10.appspot.com',
    iosBundleId: 'com.example.fashtion.RunnerTests',
  );
}
